name: Login to Azure
description: Login to Azure using environment variables for a Client ID.
runs:
  using: "composite"
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
