name: Test Prompts with Promptflow
# modeled on https://github.com/Azure/llmops-gha-demo/blob/e87bec55c8ba3468e5d20668b712117b2ba17f7b/.github/workflows/deploy-pf-online-endpoint-pipeline.yml

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - federated-github-cred

env: 
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }} 
  OPENAI_ENDPOINT: ${{ vars.OPENAI_ENDPOINT }}
  AISEARCH_KEY: ${{ secrets.AISEARCH_KEY }} 
  AISEARCH_ENDPOINT: ${{ vars.AISEARCH_ENDPOINT }}


jobs:

  register-model-in-azureml:
    runs-on: ubuntu-latest 
    steps:
    - name: Azure login
      uses: azure/login@v1
    - name: Install az ml extension
      run: az account show