name: Test Prompts with Promptflow
# modeled on https://github.com/Azure/llmops-gha-demo/blob/e87bec55c8ba3468e5d20668b712117b2ba17f7b/.github/workflows/deploy-pf-online-endpoint-pipeline.yml

on:
  workflow_dispatch:
    inputs:
      search_index:
        description: 'Search index to be used' # description of the input
        required: true
        default: 'patents' # default value if not specified
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
      id-token: write
      contents: read

env: 
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }} 
  OPENAI_ENDPOINT: ${{ vars.OPENAI_ENDPOINT }}
  AISEARCH_KEY: ${{ secrets.AISEARCH_KEY }} 
  AISEARCH_ENDPOINT: ${{ vars.AISEARCH_ENDPOINT }}
  AISEARCH_INDEX: ${{ github.event.inputs.search_index || ${{ vars.AISEARCH_INDEX }} || 'patents' }} 
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  AZURE_ML_WORKSPACE: ${{ vars.AZURE_ML_WORKSPACE }}
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

jobs:
  run-promptflow:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: chat-with-patents
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: "check settings"
      run: |
        set -u
        for i in \
          OPENAI_KEY \
          OPENAI_ENDPOINT \
          AISEARCH_KEY \
          AISEARCH_ENDPOINT \
          AZURE_RESOURCE_GROUP \
          AZURE_ML_WORKSPACE \
          AZURE_CLIENT_ID \
          AZURE_TENANT_ID \
          AZURE_SUBSCRIPTION_ID \
          ; do echo "Checking \$$i is set..."; printenv $i > /dev/null
        done
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'
    - name: Install promptflow
      run: pip install -r requirements.txt
    - name: Install local keyring
      run: pip install keyrings.alt
    - name: Configure promptflow connections
      run: |
        pf connection create --file ../connections/azure_openai.yaml --name open_ai_connection --set api_key=${{ env.OPENAI_KEY }} api_base=${{ env.OPENAI_ENDPOINT }}
        pf connection create --file ../connections/azure_ai_search.yaml --name ai_search_connection --set api_key=${{ env.AISEARCH_KEY }} api_base=${{ env.AISEARCH_ENDPOINT }}
    - name: Test promptflow run
      run: pf flow test --flow . --inputs search_index="${{ env.AISEARCH_INDEX }}"
    - name: Run promptflow batch
      run: pf run create --file batch_run.yaml --name batch_run --inputs search_index="${{ env.AISEARCH_INDEX }}"
    - name: Run promptflow evaluation
      run: pf run create --file ../rag-evaluation-flow/evaluation_run.yaml --run batch_run --name evaluation_run 
    - name: Visualize promptflow runs
      # When run non-interactively, this produces an HTML file in /tmp
      run: |
        pf run visualize --name batch_run 
        pf run visualize --name evaluation_run 
    - name: Archive promptflow run visualizations
      uses: actions/upload-artifact@v3
      with:
        name: promptflow-visualizations
        path: /tmp/*.html

  register-model-in-azureml:
    needs: run-promptflow
    runs-on: ubuntu-latest 
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      id: azlogin
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    - name: Set Azure CLI defaults
      run: az configure --defaults group=${{env.AZURE_RESOURCE_GROUP}} workspace=${{env.AZURE_ML_WORKSPACE}}
    - name: Register promptflow model
      run: az ml model create --file chat-with-patents/deployment/model.yaml
