name: Test Prompts with Promptflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-pf:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: chat-with-patents
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'
    - name: List current directory
      run: ls
    - name: Install promptflow
      run: pip install -r requirements.txt
    - name: Test promptflow run
      run: pf flow test --flow .
